### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by traceferre** [tiy-curtissimo/rolodex-of-terror-ui#3]
We have made the changes to ensure first name, last name, phone number, address street, address city and the foreign keys are not nullable.  However, empty Strings can still be passed in.  We can set a min length annotation on the variable on the back-end, OR you could make these fields required on your end.  Thoughts?

**Comment by tiy-curtissimo** [comment]
I will make them required on my end. However, you can *never* trust input from another system, so you should probably put guards in the Java code, too.
